### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PapaTutuWawa** [PapaTutuWawa/moxxyv2#2]
## Pre-Alpha 0.0.1
  - [x] Improve tests
    - [x] Test every XEP implemented
    - [x] Add tests for connection failures/unexpected events
  - [x] Make the linter happy
  - [x] Stub out not implemented features
    - [x] Registration
    - [x] Image sending preview
- [x] Fix service crashing when the service is started on boot
- [x] ~~Fix connection failing after boot~~ It's not failing, the notification is just wrongly set to "disconnected"
- [x] Pull the Moxxy specific bits out of `lib/xmpp/xeps/xep_0030.dart` and `lib/xmpp/xeps/xep_0115.dart`

## Pre-Alpha 0.0.2
See #3 

## Alpha 0.1.0
See #5 

## Alpha 0.2.0
See #7 

## Concrete Things To Be Done
- [x] Figure out a better logging system (Maybe do something like Monal)
- [ ] Work through most TODOs
- [ ] Remove widget specific theming and do it globally
- [x] Finally fix the sizing of UI elements
- [x] #4 
- [ ] Group notifications
- [ ] Tapping a message notification should take you to the respective chat
- [x] Better management of presence subscriptions
  - [x] We should strive to achieve a "both" subscription
- [ ] Sometimes messages repeat after hot-restarting?
  - It this just a development problem?
- [x] Every media file updates the last message body to "Image"
- [x] Send Chat Markers (and make that configurable)
- [x] ~~Images sometimes have their upper left corner not rounded enough~~
- [x] Rework the communication of foreground app code and the background services
  - Maybe have a single event class that bundles other classes?
- [ ] There might still be a reconnection issue
- [ ] Replace the `StanzaHandler` system with the `EventHandler`
- [ ] Replace the custom awaitable implementation with the `AwaitableDataSender`
- [x] Everytime the conversation page is updated, the list gets re-created and thus widgets get recreated => Split up the page into two `BlocBuilder`s

## At Some Point
- [ ] Message styling
- [x] OMEMO
- [x] Message Reactions
- [ ] Stickers
- [ ] Optimize startup time
  - Maybe move the XMPP code into it's own thread still 
- [ ] Switch to semver instead of just doing whatever
- [ ] Make registration possible
  - [ ] IBR
  - [ ] Easy User Onboarding
  - [ ] Allow creating invites?
- [ ] Groupchats (MUC or MIX?)
- [ ] MAM
- [x] Notify the user if the connection is lost after waiting 30 minutes with no reconnection
- [ ] Push Notifications
  - Use [Unified Push](https://unifiedpush.org/)
- [x] Chat backgrounds
- [ ] i18n
- [x] Animations
- [x] Extract `lib/xmpp` into its own library
  - Only after OMEMO is implemented as OMEMO requires a big rework of the `StanzaHandler` system to allow them to pass data between each other and also intercept stanzas before they are sent
- [ ] Link Previews

## Perhaps
- [ ] ~~BoSH and/or~~ WebSockets
- [ ] iOS
  - [ ] Replace Android specific code with cross-platform code

## Interesting Flutter Packages
- `photo_view`: For allowing users to tap an image and see it bigger
- `flutter_blurhash`: Maybe "extend" XEP-0385 to allow the usage of blurhash as a thumbnail
- `another_flushbar`: To replace our custom snackbar
- `video_thumbnail`: To generate a thumbnail after downloading/before uploading a video

**Comment by PapaTutuWawa** [comment]
Issue moved to here: https://codeberg.org/moxxy/moxxyv2/issues/4
